travis:
  secure:
    BINSTAR_TOKEN: AN9Cnw1krisqE5wC+yy/2URbGVRop9fnXb3+AT9ShXYrR6VbL3rs4gVpxUoh0OVvQ5Ep/mqBYnKNrgNnhetrmjMlETcdE660Kuf8erUFY0Clk9eOtOHQpSGmzG0L5qU+pTSfQKb52gzD24XMyszAtxbmmhWpoTe3tTrUtWEkjZ74FUWp1mtYsFBDfK6o7R3vn7CLXetFFbdwamqUDxJpFNv5o5A4sRaGSDnCQ+auTH3BMeaUWXAzfvme6MOsUNseIidUUJZLuuqSwEUNqJ8AsM83jwBaWfJfUM3irjI0fiJMcF+t6HLJr+bBadUWWf2mnaMAkx+OjbJg/tCTw39h6UXvyS3x3TjmBjArwS01z4XwfBUU+SGi0bsRpeX+rjLigRQ7orZ3aTYRgG35jhmgGu4JlZEZiWQoXj50Ec0lhno5APBMn2XMUrGsBnln79Q3rwaAqWdMkLE7ZoJu8eGXRvtUBMoE5DAsNbMnTERIeVdXBukXk6+T27mQO6A3sEVWLBm6r1KkgFNsm5F+ByWt7oz+qx482wQMWgrQqJLBknyjx+tgZfo9oSx285t/VoL+/tG0xAP56Kdn226jU1porozbzyg6Ig9eR8ey4cmm6CmYTEQPU1B1y5wbpU7rKVXIJ2frWUFmQufxBIYXzSlObvkRbxOsezkhGFyajPLwAYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
