travis:
  secure:
    BINSTAR_TOKEN: nx2qTpgwc2btADnUOYnnKhk6wlwonYsq66CqP5vgeMBwXL5KXh2yC4RhZa3cfOEcDGLQiNClvwPs/JyrJsl5VxFJrUbj35+opSlZoiOVsqEIQuQbEVr5eHomnXlCyvjLFSV/1J7+OwETIri2e2E+JqSZbXg37cpIXCyzUaRegusfHzNOUkVygUbRFJHBIarufRhJH8zLpJSdPhd0A5fxBZzgvhqN/UM1uhXkLXTYec6FHq/HvhbXL4nw41VBXtJPUeX26dQcFBEeUJKrkIZkP0MfzJ1OndEpqXf8DP6pRoB5dVoE+8n8vderXlEXJFAQ/yp0iIBzyy7Qo6bSVTYFzNve6W7d1YxyN0DTV5RjfYXDfZoeH7TlgNy/Zdu7gV18FK+GDdRdaSYL8jXd8iPx4lkohj2lvTrBuMlJnwYKl+H6v1SBa6QKE70+CCGDwo+vJ36cd6fiXxwZS7QLN5/ivhcIDrwAtgG2cOIBGWGCe0w4Pc6bmZXa1puewBSo1w+56erJCmkOtO8ADjyVRTDXAurlou3ilrkwULyhF/W+/vAa0fGJhoXUkCQKmAxmiAIvyLzgc9F7L/ZgXjdsMNsYkEc5hjygy6QDtLJIX88pHAHM+ziNS4x3EPx7cN2o7XJ8YVdj985uZmlYP3vV0SVBjqA0I4a7cAcTdkCI8walXP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
